Jewel ecom/jewel/cart/urls.py
# urls.py
from cart import views
from django.urls import path


urlpatterns = [

    # Your other URL patterns
]

Jewel ecom/jewel/jewel/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('wishlist.urls')),
    path('', include('coupon.urls')),
    path('', include('cadmin.urls')),
    path('', include('user.urls')),
    path('accounts/', include('allauth.urls')),  # Include allauth URLs
     path('', include('payments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Jewel ecom/jewel/user/urls.py
# urls.py
from django.urls import include, path
from .views import add_address,wallet_transaction_history, add_to_cart, return_order,calculate_discounted_total,  cancel_order,  category_product_list, checkout, delete_address, delete_cart_item, edit_address, edit_profile, forget_password, forgot_password, get_messages, logout_view, order_detail, order_history, order_successful, product_detail, resend_otp, reset_password, search_products, signin, signup, update_cart, user_profile, verify_otp,home, verify_otp_forget_password, view_cart
from payments.views import * 


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('', home, name='home'),
    path('verify-otp/', verify_otp, name='verify_otp'),
    path('signin/', signin, name='signin'),
 path('accounts/profile/', home, name='home'),  # Adjust 'profile_view' with your actual view
     path('accounts/', include('allauth.urls')),
       path('resend-otp/', resend_otp, name='resend_otp'),
      path('category/<int:category_id>/', category_product_list, name='category_product_list'),
          path('logout/',logout_view, name='logout'),
      path('product/<int:product_id>/', product_detail, name='product_detail'),

   path('calculate_discounted_total/', calculate_discounted_total, name='calculate_discounted_total'),  # Add this line
       

         path('user_profile/', user_profile, name='user_profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),

    path('forgot_password/', forgot_password, name='forgot_password'),


 path('add_to_cart/', add_to_cart, name='add_to_cart'),
  path('view_cart/', view_cart, name='view_cart'),
    path('update_cart/', update_cart, name='update_cart'),
    path('delete_cart_item/', delete_cart_item, name='delete_cart_item'),

        path('search/', search_products, name='search_products'),

  path('checkout/', checkout, name='checkout'),
 path('order_successful/<int:order_id>/', order_successful, name='order_successful'),
 path('get_messages/', get_messages, name='get_messages'),

 path('order/<int:order_id>/', order_detail, name='order_detail'),
    path('order/<int:order_id>/cancel/', cancel_order, name='cancel_order'),
        path('order/<int:order_id>/return/', return_order, name='return_order'),
    path('order/history/', order_history, name='order_history'),

   
       path('forget-password/', forget_password, name='forget_password'),
    path('verify-otp-forget-password/', verify_otp_forget_password, name='verify_otp_forget_password'),
      path('reset-password/', reset_password, name='reset_password'),

    path('payment_page/<int:order_id>/', payment_page, name='payment_page'),
    path('process_cod_payment/<int:order_id>/', process_cod_payment, name='process_cod_payment'),
    path('process_razorpay_payment/<int:order_id>/', process_razorpay_payment, name='process_razorpay_payment'),
    path('generate-pdf-invoice/<int:order_id>/', generate_invoice_pdf, name='generate_invoice_pdf'),


 path('add_address/', add_address, name='add_address'),
    path('edit_address/<int:address_id>/', edit_address, name='edit_address'),
    path('delete_address/<int:address_id>/', delete_address, name='delete_address'),
    
    # Add other URLs as needed

     path('process_razorpay_payment/<int:order_id>/', process_razorpay_payment, name='process_razorpay_payment'),
    path('payment_success/<int:order_id>/', payment_success, name='payment_success'),
    path('payment_failure/<int:order_id>/', payment_failure, name='payment_failure'),
        path('product/<int:product_id>/rate/', create_rating, name='create_rating'),
          path('create_reason/<int:order_id>/', create_reason, name='create_reason'),
           path('wallet/transaction-history/', wallet_transaction_history, name='wallet_transaction_history'),
]

Jewel ecom/jewel/user/models.py
# models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import ValidationError
from product.models import Products, Size

class User(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True,unique=True)
    is_verified = models.BooleanField(default=False)
    otp = models.CharField(max_length=6, blank=True, null=True)
    otp_generated_at = models.DateTimeField(null=True, blank=True)

    # Add related_name to avoid clashes
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name='custom_user_set',  # Add a related_name
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='custom_user_set',  # Add a related_name
    )
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='addresses')
    street_address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.street_address}, {self.city}, {self.state}, {self.postal_code}, {self.country}"
    

    from django.db import models
from user.models import User

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 
    def save(self, *args, **kwargs):
        self.updated_at = timezone.now()


        return super().save(*args, **kwargs)
    
    def total_cart_value(self):
        # Calculate the total value of items in the cart
        total_value = round(sum(item.total_price() for item in self.items.all()),0)
        return total_value
    

from django.db import models
from django.utils import timezone
from product.models import Products, Size
from user.models import User

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    updated_at = models.DateTimeField(auto_now=True)  # Set auto_now to True
    offer_price = models.DecimalField(max_digits=15, decimal_places=2, default=0)  # New field for offer price


    def clean(self):
        # Check if the selected quantity exceeds the available stock
        if self.quantity > self.size.stock:
            raise ValidationError(f"Only {self.size.stock} units available in stock for {self.size.measurement}")


    def __str__(self):
        return f"{self.quantity} x {self.size.measurement} of {self.product.name} in {self.cart}"


    class Meta:
        unique_together = ('cart', 'product', 'size')  # Ensure unique items in the cart


    def total_price(self):
        return round(self.offer_price * self.quantity,0)


    def save(self, *args, **kwargs):
        # Check if the selected quantity exceeds the maximum allowed per person
        max_quantity_per_person = 3  # You can adjust this value
        user_cart_items = CartItem.objects.filter(cart=self.cart, product=self.product).exclude(pk=self.pk)
        total_quantity = sum(item.quantity for item in user_cart_items) + self.quantity


        if total_quantity > max_quantity_per_person:
            raise ValidationError(f"You can add only up to {max_quantity_per_person} units of item to your cart.")
            

        super().save(*args, **kwargs)


# models.py




from django.db import models
from user.models import User
from product.models import Size, Products


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    original_street_address = models.CharField(max_length=255, blank=True, null=True)
    original_city = models.CharField(max_length=100, blank=True, null=True)
    original_state = models.CharField(max_length=100, blank=True, null=True)
    original_postal_code = models.CharField(max_length=20, blank=True, null=True)
    original_country = models.CharField(max_length=100, blank=True, null=True)
    coupon_code = models.CharField(max_length=255, blank=True, null=True)
    coupon_discount  = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    delivery_charge = models.DecimalField(max_digits=15, decimal_places=2, default=0)  # New field for delivery charge

    COD = 'COD'
    RAZORPAY = 'Razorpay'
    WALLET = 'Wallet'
    WALLET_AND_RAZORPAY = 'WalletandRazorpay'

    PAYMENT_METHOD_CHOICES = [
    (COD, 'COD'),
    (RAZORPAY, 'Razorpay'),
    (WALLET, 'Wallet'),
    (WALLET_AND_RAZORPAY, 'Wallet and Razorpay'),  # Corrected value
    ]

    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, default=COD)

# Payment status choices
    PENDING = 'Pending'
    COMPLETED = 'Completed'
    REFUNDED = 'Refunded'

    PAYMENT_STATUS_CHOICES = [
    (PENDING, 'Pending'),
    (REFUNDED, 'Refunded'),
    (COMPLETED, 'Completed'),
    ]

    payment_status = models.CharField(max_length=20, choices=PAYMENT_STATUS_CHOICES, default=PENDING)

    
    # Status choices
    PROCESSING = 'Processing'
    SHIPPED = 'Shipped'
    DELIVERED = 'Delivered'
    CANCELLED = 'Cancelled'
    RETURNED = 'Returned'


    STATUS_CHOICES = [
        (PROCESSING, 'Processing'),
        (SHIPPED, 'Shipped'),
        (DELIVERED, 'Delivered'),
        (CANCELLED, 'Cancelled'),
        (RETURNED, 'Returned'),

    ]


    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=PROCESSING)
    wallet = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    cod = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    razor = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    razorpay_order_id = models.CharField(max_length=255, blank=True, null=True)  # Add this line
    original_total_value = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    discounted_total = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_value = models.DecimalField(max_digits=15, decimal_places=2, default=0)  # Add total order value field
    
    
    def save(self, *args, **kwargs):
         if not self.id:
        # Save original address and total value when the order is created
            self.original_street_address = self.address.street_address
            self.original_city = self.address.city
            self.original_state = self.address.state
            self.original_postal_code = self.address.postal_code
            self.original_country = self.address.country
            
      
         super().save(*args, **kwargs)
    
    def __str__(self):
        return f"Order #{self.id} - {self.user.username} - Status: {self.status}"
  
    def cancel_order(self):
        # Method to cancel the order
        if self.status == self.PROCESSING:
            # Restock products
            for item in self.items.all():
                item.size.stock += item.quantity
                item.size.save()

            self.status = self.CANCELLED
            self.save()

            if self.payment_status == 'Completed' :
                user_wallet = self.user.wallet
                user_wallet.add_funds(self.discounted_total)
                self.payment_status = 'Refunded'
                self.save()

            return True
        return False


  
    def ship_order(self):
        # Method to cancel the order
        if self.status == self.PROCESSING:
            # Restock products
            
            self.status = self.SHIPPED
            self.save()
            return True

        return False

  
    def deliver_order(self):
        # Method to cancel the order
        if self.status == self.SHIPPED:
            self.status = self.DELIVERED
            self.save()

            if self.payment_status == 'Pending' :
                self.payment_status = 'Completed'
                self.save()
            return True
        return False


    def return_order(self):
        # Method to return the order
        if self.status == self.DELIVERED:
            # Restock products
            for item in self.items.all():
                item.size.stock += item.quantity
                item.size.save()

            self.status = self.RETURNED
            self.save()

            if self.payment_status == self.COMPLETED:
                # Refund the payment if it was completed
                user_wallet = self.user.wallet
                user_wallet.add_funds(self.discounted_total)
                self.payment_status = self.REFUNDED
                self.save()

            return True
        return False


    def get_order_history(self):
        # Method to get order history for the user
        return Order.objects.filter(user=self.user).order_by('-created_at')

    def get_order_status_display(self):
        # Method to get display text for order status
        return dict(self.STATUS_CHOICES)[self.status]
    
    def total_value(self):
        # Method to calculate the total order value
        total_value = sum(item.total_price() for item in self.items.all())
        self.total_value = total_value
        self.save()
        return total_value


from django.core.exceptions import ValidationError

from product.models import Size, Products

class OrderItem(models.Model):

Jewel ecom/jewel/templates/user/user/address_form.html
{% extends 'user/base.html' %}

{% block content %}
  <div class="container mt-3">
    <h2 class="mb-4">Add/Edit Address</h2>
    <form method="post">
      {% csrf_token %}
      <table class="table">
        <!-- Loop through form fields to render them in table rows -->
        {% for field in form %}
          <tr>
            <td>{{ field.label_tag }}</td>
            <td>{{ field }}</td>
          </tr>
        {% endfor %}
      </table>
      <button type="submit" class="btn btn-primary">Save</button>
    </form>

 
  </div>
{% endblock %}

Jewel ecom/jewel/templates/user/user/edit_profile.html
{% extends 'user/base.html' %}

{% block content %}
  <style>
    .container {
      max-width: 600px;
      margin: auto;
    }

    .mb-4 {
      margin-bottom: 1.5rem;
    }

    .profile-form {
      width: 100%;
      max-width: 400px;
      margin: auto;
    }

    /* Additional Styles */
    .profile-form label {
      margin-bottom: 0.5rem;
      font-weight: bold;
    }

    .profile-form input {
      width: 100%;
      padding: 0.375rem 0.75rem;
      margin-bottom: 1rem;
      font-size: 1rem;
      line-height: 1.5;
      color: #495057;
      background-color: #fff;
      background-clip: padding-box;
      border: 1px solid #ced4da;
      border-radius: 0.25rem;
      transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .profile-form input:focus {
      border-color: #007bff;
      outline: 0;
      box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
    }

    .btn {
      display: inline-block;
      font-weight: 400;
      color: #fff;
      text-align: center;
      vertical-align: middle;
      user-select: none;
      background-color: #007bff;
      border: 1px solid #007bff;
      padding: 0.375rem 0.75rem;
      font-size: 1rem;
      line-height: 1.5;
      border-radius: 0.25rem;
      transition: color 0.15s, background-color 0.15s, border-color 0.15s, box-shadow 0.15s;
      cursor: pointer;
    }

    .btn:hover {
      background-color: #0056b3;
      border-color: #0056b3;
    }
  </style>

  <div class="container mt-4">
    <h2 class="mb-4">Edit Profile</h2>
    <form method="post" class="profile-form">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_username">Username:</label>
        <input type="text" id="id_username" name="username" value="{{ user.username }}" required>
      </div>

      <div class="form-group">
        <label for="id_email">Email:</label>
        <input type="email" id="id_email" name="email" value="{{ user.email }}" required>
      </div>

      <div class="form-group">
        <label for="id_phone_number">Phone Number:</label>
        <input type="tel" id="id_phone_number" name="phone_number" value="{{ user.phone_number }}" required>
      </div>
      
      <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
  </div>
{% endblock %}

Jewel ecom/jewel/templates/user/user/forget_password.html
{% extends 'user/base.html' %}

{% block title %}Forget Password{% endblock title %}

{% block content %}
  <div class="container mt-3">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h2 class="mb-4">Forget Password</h2>
        <p>Enter your email or phone number to reset your password.</p>

        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
        
        <form method="post" action="{% url 'forget_password' %}">
          {% csrf_token %}
          
          <p>
            {{ form.email_or_phone.label_tag }} {{ form.email_or_phone }}
            {% if form.email_or_phone.errors %}
              <span class="text-danger">{{ form.email_or_phone.errors }}</span>
            {% endif %}
          </p>
          
          <button type="submit" class="btn btn-primary mt-3">Send OTP</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

Jewel ecom/jewel/templates/user/user/reset_password.html
{% extends 'user/base.html' %}

{% block title %}Reset Password{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Reset Password</div>

                <div class="card-body">
                    <form method="post" action="{% url 'reset_password' %}">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="new_password1" class="col-md-4 col-form-label text-md-right">{{ form.new_password1.label_tag }}</label>
                            <div class="col-md-6">
                                {{ form.new_password1 }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="new_password2" class="col-md-4 col-form-label text-md-right">{{ form.new_password2.label_tag }}</label>
                            <div class="col-md-6">
                                {{ form.new_password2 }}
                            </div>
                        </div>

                        {% if form.errors %}
                        <div class="form-group row">
                            <div class="offset-md-4 col-md-6">
                                <p class="error">{{ form.errors }}</p>
                            </div>
                        </div>
                        {% endif %}

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">Reset Password</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Jewel ecom/jewel/templates/user/user/user_profile.html
{% extends 'user/base.html' %}

{% block content %}
<div class="container mt-4">
  <div class="row align-items-center">
    <h2 class="mb-4 mr-3">User Profile</h2> <!-- Add mr-3 class for right margin -->
    <a href="{% url 'edit_profile' %}" class="btn btn-secondary">Edit Profile</a>
</div>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <th scope="row">Username:</th>
        <td>{{ user.username }}</td>
      </tr>
      <tr>
        <th scope="row">Email:</th>
        <td>{{ user.email }}</td>
      </tr>
      <tr>
        <th scope="row">Phone Number:</th>
        <td>{{ user.phone_number }}</td>
      </tr>
      <tr>
        <th scope="row">Wallet Balance:</th>
        <td>{{ wallet_balance }}</td>
      </tr>
      {% if referral_coupon_code %}
      <tr>
        <th scope="row">Referral Coupon Code:</th>
        <td>{{ referral_coupon_code }}</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <p><strong> Refer your friend using Coupon Code and grab 100 Rupees wallet money</p></strong>

  <a href="{% url 'order_history' %}" class="btn btn-info">Order History</a>
  <a href="{% url 'wallet_transaction_history' %}" class="btn btn-info">Wallet</a>
</div>


  <h2 class="mt-4 mb-3">Your Addresses</h2>
  <ul class="list-group address-list">
    {% for address in addresses %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <div>
        {{ address }}
      </div>
      <div class="address-actions">
        <a href="{% url 'edit_address' address.id %}" class="btn btn-sm btn-warning">Edit</a>
        <a href="{% url 'delete_address' address.id %}" class="btn btn-sm btn-danger">Delete</a>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>

<a href="{% url 'add_address' %}" class="btn btn-primary mt-3">Add Address</a>

<div class="profile-actions mt-3">
  <!-- Button to navigate to the checkout page -->
  <a href="{% url 'checkout' %}" class="btn btn-primary mt-3">Checkout</a>
</div>
{% endblock %}

Jewel ecom/jewel/templates/user/user/verify_otp_forget_password.html
{% extends 'user/base.html' %}

{% block title %}Verify OTP for Password Reset{% endblock title %}

{% block content %}
  <div class="container mt-3">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h2 class="mb-4">Verify OTP</h2>
        <p>Enter the OTP sent to your email or phone number to reset your password.</p>

        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
      

        <form method="post" action="{% url 'verify_otp_forget_password' %}">
          {% csrf_token %}
          {{ form.otp.label_tag }} {{ form.otp }}
          
          {% if form.errors %}
            <p class="error">{{ form.errors }}</p>
          {% endif %}

          <button type="submit" class="btn btn-primary mt-3">Verify OTP</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

Jewel ecom/jewel/templates/user/user/wallet_transaction.html
{% extends 'user/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Wallet Transaction History</h2>
    <p><strong>Opening Balance:</strong> {{ opening_balance }}</p>
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Transaction Type</th>
                <th scope="col">Amount</th>
                <th scope="col">Timestamp</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.transaction_type }}</td>
                <td>{{ transaction.amount }}</td>
                <td>{{ transaction.timestamp }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No transactions found</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <!-- Pagination -->
    <div class="pagination">
        <span class="step-links">
            {% if transactions.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ transactions.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ transactions.number }} of {{ transactions.paginator.num_pages }}.
            </span>

            {% if transactions.has_next %}
                <a href="?page={{ transactions.next_page_number }}">next</a>
                <a href="?page={{ transactions.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

    <p><strong>Current Balance:</strong> {{ current_balance }}</p>
</div>
{% endblock %}