Jewel ecom/jewel/cart/urls.py
# urls.py
from cart import views
from django.urls import path


urlpatterns = [

    # Your other URL patterns
]

Jewel ecom/jewel/jewel/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('wishlist.urls')),
    path('', include('coupon.urls')),
    path('', include('cadmin.urls')),
    path('', include('user.urls')),
    path('accounts/', include('allauth.urls')),  # Include allauth URLs
     path('', include('payments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Jewel ecom/jewel/user/urls.py
# urls.py
from django.urls import include, path
from .views import add_address,wallet_transaction_history, add_to_cart, return_order,calculate_discounted_total,  cancel_order,  category_product_list, checkout, delete_address, delete_cart_item, edit_address, edit_profile, forget_password, forgot_password, get_messages, logout_view, order_detail, order_history, order_successful, product_detail, resend_otp, reset_password, search_products, signin, signup, update_cart, user_profile, verify_otp,home, verify_otp_forget_password, view_cart
from payments.views import * 


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('', home, name='home'),
    path('verify-otp/', verify_otp, name='verify_otp'),
    path('signin/', signin, name='signin'),
 path('accounts/profile/', home, name='home'),  # Adjust 'profile_view' with your actual view
     path('accounts/', include('allauth.urls')),
       path('resend-otp/', resend_otp, name='resend_otp'),
      path('category/<int:category_id>/', category_product_list, name='category_product_list'),
          path('logout/',logout_view, name='logout'),
      path('product/<int:product_id>/', product_detail, name='product_detail'),

   path('calculate_discounted_total/', calculate_discounted_total, name='calculate_discounted_total'),  # Add this line
       

         path('user_profile/', user_profile, name='user_profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),

    path('forgot_password/', forgot_password, name='forgot_password'),


 path('add_to_cart/', add_to_cart, name='add_to_cart'),
  path('view_cart/', view_cart, name='view_cart'),
    path('update_cart/', update_cart, name='update_cart'),
    path('delete_cart_item/', delete_cart_item, name='delete_cart_item'),

        path('search/', search_products, name='search_products'),

  path('checkout/', checkout, name='checkout'),
 path('order_successful/<int:order_id>/', order_successful, name='order_successful'),
 path('get_messages/', get_messages, name='get_messages'),

 path('order/<int:order_id>/', order_detail, name='order_detail'),
    path('order/<int:order_id>/cancel/', cancel_order, name='cancel_order'),
        path('order/<int:order_id>/return/', return_order, name='return_order'),
    path('order/history/', order_history, name='order_history'),

   
       path('forget-password/', forget_password, name='forget_password'),
    path('verify-otp-forget-password/', verify_otp_forget_password, name='verify_otp_forget_password'),
      path('reset-password/', reset_password, name='reset_password'),

    path('payment_page/<int:order_id>/', payment_page, name='payment_page'),
    path('process_cod_payment/<int:order_id>/', process_cod_payment, name='process_cod_payment'),
    path('process_razorpay_payment/<int:order_id>/', process_razorpay_payment, name='process_razorpay_payment'),
    path('generate-pdf-invoice/<int:order_id>/', generate_invoice_pdf, name='generate_invoice_pdf'),


 path('add_address/', add_address, name='add_address'),
    path('edit_address/<int:address_id>/', edit_address, name='edit_address'),
    path('delete_address/<int:address_id>/', delete_address, name='delete_address'),
    
    # Add other URLs as needed

     path('process_razorpay_payment/<int:order_id>/', process_razorpay_payment, name='process_razorpay_payment'),
    path('payment_success/<int:order_id>/', payment_success, name='payment_success'),
    path('payment_failure/<int:order_id>/', payment_failure, name='payment_failure'),
        path('product/<int:product_id>/rate/', create_rating, name='create_rating'),
          path('create_reason/<int:order_id>/', create_reason, name='create_reason'),
           path('wallet/transaction-history/', wallet_transaction_history, name='wallet_transaction_history'),
]

Jewel ecom/jewel/coupon/models.py
from decimal import Decimal
from django.db import models
from user.models import User



class Coupon(models.Model):
    # Existing fields
    code = models.CharField(max_length=20, unique=True)
    discount_type = models.CharField(max_length=20, choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')])
    discount_amount = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    minimum_purchase_amount = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    maximum_discount_amount = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    valid_from = models.DateTimeField()
    valid_until = models.DateTimeField()

    # Additional fields for first purchase coupon


    def __str__(self):
        return self.code
    
    @staticmethod
    def calculate_discounted_total(discount_type, total_cart_value, discount_amount, discount_percentage):
        total_cart_value = Decimal(str(total_cart_value))  # Convert total_cart_value to Decimal

        if discount_type == 'fixed':
            discounted_total = max(Decimal('0.00'), total_cart_value - Decimal(str(discount_amount)))
        elif discount_type == 'percentage':
            discount_amount = total_cart_value * (Decimal(str(discount_percentage)) / Decimal('100.00'))
            discounted_total = max(Decimal('0.00'), total_cart_value - discount_amount)
        else:
            discounted_total = total_cart_value

        return float(discounted_total)  # Convert Decimal to float before returning



class ReferralCoupon(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    coupon_code = models.CharField(max_length=20, unique=True)
    referrals_made = models.PositiveIntegerField(default=0)  # Track the number of referrals made by the user
    is_used = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

from product.models import Products,Category
from django.core.validators import MaxValueValidator

class ProductOffers(models.Model):
    product = models.OneToOneField(Products, on_delete=models.CASCADE, related_name='offer')
    name = models.CharField(max_length=100, default="Default Offer Name")
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2, validators=[MaxValueValidator(50)])
    start_date = models.DateField()
    end_date = models.DateField()

class CategoryOffers(models.Model):
    category = models.OneToOneField(Category, on_delete=models.CASCADE, related_name='offer')
    name = models.CharField(max_length=100, default="Default Offer Name")  # Provide a default value
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2 ,validators=[MaxValueValidator(50)])
    start_date = models.DateField()
    end_date = models.DateField()

Jewel ecom/jewel/user/models.py
# models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import ValidationError
from product.models import Products, Size

class User(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True,unique=True)
    is_verified = models.BooleanField(default=False)
    otp = models.CharField(max_length=6, blank=True, null=True)
    otp_generated_at = models.DateTimeField(null=True, blank=True)

    # Add related_name to avoid clashes
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name='custom_user_set',  # Add a related_name
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='custom_user_set',  # Add a related_name
    )
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='addresses')
    street_address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.street_address}, {self.city}, {self.state}, {self.postal_code}, {self.country}"
    

    from django.db import models
from user.models import User

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 
    def save(self, *args, **kwargs):
        self.updated_at = timezone.now()


        return super().save(*args, **kwargs)
    
    def total_cart_value(self):
        # Calculate the total value of items in the cart
        total_value = round(sum(item.total_price() for item in self.items.all()),0)
        return total_value
    

from django.db import models
from django.utils import timezone
from product.models import Products, Size
from user.models import User

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    updated_at = models.DateTimeField(auto_now=True)  # Set auto_now to True
    offer_price = models.DecimalField(max_digits=15, decimal_places=2, default=0)  # New field for offer price


    def clean(self):
        # Check if the selected quantity exceeds the available stock
        if self.quantity > self.size.stock:
            raise ValidationError(f"Only {self.size.stock} units available in stock for {self.size.measurement}")


    def __str__(self):
        return f"{self.quantity} x {self.size.measurement} of {self.product.name} in {self.cart}"


    class Meta:
        unique_together = ('cart', 'product', 'size')  # Ensure unique items in the cart


    def total_price(self):
        return round(self.offer_price * self.quantity,0)


    def save(self, *args, **kwargs):
        # Check if the selected quantity exceeds the maximum allowed per person
        max_quantity_per_person = 3  # You can adjust this value
        user_cart_items = CartItem.objects.filter(cart=self.cart, product=self.product).exclude(pk=self.pk)
        total_quantity = sum(item.quantity for item in user_cart_items) + self.quantity


        if total_quantity > max_quantity_per_person:
            raise ValidationError(f"You can add only up to {max_quantity_per_person} units of item to your cart.")
            

        super().save(*args, **kwargs)


# models.py




from django.db import models
from user.models import User
from product.models import Size, Products


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    original_street_address = models.CharField(max_length=255, blank=True, null=True)
    original_city = models.CharField(max_length=100, blank=True, null=True)
    original_state = models.CharField(max_length=100, blank=True, null=True)
    original_postal_code = models.CharField(max_length=20, blank=True, null=True)
    original_country = models.CharField(max_length=100, blank=True, null=True)
    coupon_code = models.CharField(max_length=255, blank=True, null=True)
    coupon_discount  = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    delivery_charge = models.DecimalField(max_digits=15, decimal_places=2, default=0)  # New field for delivery charge

    COD = 'COD'
    RAZORPAY = 'Razorpay'
    WALLET = 'Wallet'
    WALLET_AND_RAZORPAY = 'WalletandRazorpay'

    PAYMENT_METHOD_CHOICES = [
    (COD, 'COD'),
    (RAZORPAY, 'Razorpay'),
    (WALLET, 'Wallet'),
    (WALLET_AND_RAZORPAY, 'Wallet and Razorpay'),  # Corrected value
    ]

    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, default=COD)

# Payment status choices
    PENDING = 'Pending'
    COMPLETED = 'Completed'
    REFUNDED = 'Refunded'

    PAYMENT_STATUS_CHOICES = [
    (PENDING, 'Pending'),
    (REFUNDED, 'Refunded'),
    (COMPLETED, 'Completed'),
    ]

    payment_status = models.CharField(max_length=20, choices=PAYMENT_STATUS_CHOICES, default=PENDING)

    
    # Status choices
    PROCESSING = 'Processing'
    SHIPPED = 'Shipped'
    DELIVERED = 'Delivered'
    CANCELLED = 'Cancelled'
    RETURNED = 'Returned'


    STATUS_CHOICES = [
        (PROCESSING, 'Processing'),
        (SHIPPED, 'Shipped'),
        (DELIVERED, 'Delivered'),
        (CANCELLED, 'Cancelled'),
        (RETURNED, 'Returned'),

    ]


    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=PROCESSING)
    wallet = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    cod = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    razor = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    razorpay_order_id = models.CharField(max_length=255, blank=True, null=True)  # Add this line
    original_total_value = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    discounted_total = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_value = models.DecimalField(max_digits=15, decimal_places=2, default=0)  # Add total order value field
    
    
    def save(self, *args, **kwargs):
         if not self.id:
        # Save original address and total value when the order is created
            self.original_street_address = self.address.street_address
            self.original_city = self.address.city
            self.original_state = self.address.state
            self.original_postal_code = self.address.postal_code
            self.original_country = self.address.country
            
      
         super().save(*args, **kwargs)
    
    def __str__(self):
        return f"Order #{self.id} - {self.user.username} - Status: {self.status}"
  
    def cancel_order(self):
        # Method to cancel the order
        if self.status == self.PROCESSING:
            # Restock products
            for item in self.items.all():
                item.size.stock += item.quantity
                item.size.save()

            self.status = self.CANCELLED
            self.save()

            if self.payment_status == 'Completed' :
                user_wallet = self.user.wallet
                user_wallet.add_funds(self.discounted_total)
                self.payment_status = 'Refunded'
                self.save()

            return True
        return False


  
    def ship_order(self):
        # Method to cancel the order
        if self.status == self.PROCESSING:
            # Restock products
            
            self.status = self.SHIPPED
            self.save()
            return True

        return False

  
    def deliver_order(self):
        # Method to cancel the order
        if self.status == self.SHIPPED:
            self.status = self.DELIVERED
            self.save()

            if self.payment_status == 'Pending' :
                self.payment_status = 'Completed'
                self.save()
            return True
        return False


    def return_order(self):
        # Method to return the order
        if self.status == self.DELIVERED:
            # Restock products
            for item in self.items.all():
                item.size.stock += item.quantity
                item.size.save()

            self.status = self.RETURNED
            self.save()

            if self.payment_status == self.COMPLETED:
                # Refund the payment if it was completed
                user_wallet = self.user.wallet
                user_wallet.add_funds(self.discounted_total)
                self.payment_status = self.REFUNDED
                self.save()

            return True
        return False


    def get_order_history(self):
        # Method to get order history for the user
        return Order.objects.filter(user=self.user).order_by('-created_at')

    def get_order_status_display(self):
        # Method to get display text for order status
        return dict(self.STATUS_CHOICES)[self.status]
    
    def total_value(self):
        # Method to calculate the total order value
        total_value = sum(item.total_price() for item in self.items.all())
        self.total_value = total_value
        self.save()
        return total_value


from django.core.exceptions import ValidationError

from product.models import Size, Products

class OrderItem(models.Model):

Jewel ecom/jewel/templates/user/order/create_rating.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'user/base.html' %}

{% block content %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Rating</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            padding: 20px;
        }
        h1 {
            color: #333;
            text-align: center;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        label {
            display: block;
            margin-bottom: 10px;
        }
        input[type="text"],
        textarea {
            width: 100%;
            padding: 8px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Create Rating for {{ product.name }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Rating</button>
    </form>
</body>
</html>
{% endblock %}

Jewel ecom/jewel/templates/user/order/create_reason.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Reason</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        form {
            margin-top: 20px;
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input[type="text"],
        select {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Create Reason for Cancellation</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        
            <button type="submit" onclick="return confirm('Are you sure you want to cancel this order?')">Submit Reason</button>
        </form>
    </div>
</body>
</html>

Jewel ecom/jewel/templates/user/order/order_detail.html
{% extends 'user/base.html' %}

{% block content %}
<style>
  .container {
    max-width: 800px;
    margin: auto;
  }

  .mb-4 {
    margin-bottom: 1.5rem;
  }

  .card-header h3 {
    margin-bottom: 0;
  }

  .card-body p {
    margin-bottom: 0.5rem;
  }

  .ordered-items th,
  .ordered-items td {
    text-align: center;
  }

  .cancel-order-btn {
    margin-top: 1rem;
  }

  .total-cart-value {
    font-size: 1.2rem;
    font-weight: bold;
  }
</style>

{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
  {{ message }}
</div>
{% endfor %}

<div class="mt-3">
  

  <a href="{% url 'home' %}" class="btn btn-primary">Continue Shopping</a>
</div>

<div class="container mt-4">
  <h2 class="mb-4">Order Details</h2>

  <div class="card">
    <div class="card-header bg-info text-white">
      <h3 class="mb-0">Order Information</h3>
    </div>
    <div class="card-body">
      <table class="table">
        <tbody>
          <tr>
            <th scope="row">Order ID:</th>
            <td>{{ order.id }}</td>
          </tr>
          <tr>
            <th scope="row">User:</th>
            <td>{{ order.user.username }}</td>
          </tr>
          <tr>
            <th scope="row">Address:</th>
            <td>{{ order.original_street_address }}, {{ order.original_city }}, {{ order.original_state }}, {{ order.original_postal_code }}, {{ order.original_country }}</td>
          </tr>
          <tr>
            <th scope="row">Status:</th>
            <td>{{ order.status }}</td>
          </tr>
          <tr>
            <th scope="row"> Order Value after discount:</th>
            <td>{{ order.discounted_total }}</td>
          </tr>
          {% if order.delivery_charge > 0 %}
          <tr>
              <td><strong>Delivery charge:</strong></td>
              <td>{{ order.delivery_charge }}</td>
          </tr>  {% endif %}
          {% if order.coupon_code %}
            <tr>
              <th scope="row">Coupon Applied:</th>
              <td>{{ order.coupon_code }}</td>
            </tr>
            <tr>
              <th scope="row">Discount:</th>
              <td>{{ order.coupon_discount }}</td>
            </tr>
          {% else %}
            <tr>
              <th scope="row">Coupon Applied:</th>
              <td>No Coupon Applied</td>
            </tr>
          {% endif %}
          <tr>
            <th scope="row">Payment Status:</th>
            <td>{{ order.get_payment_status_display }}</td>
          </tr>
          <tr>
            <th scope="row">Payment Method:</th>
            <td>{{ order.get_payment_method_display }}</td>
          </tr>
          {% if order.status == 'Delivered' %}
            <tr>
              <td colspan="2">
                <a href="{% url 'return_order' order.id %}" class="btn btn-warning" onclick="return confirm('Are you sure you want to return this order?')">Return Order</a>
              </td>
            </tr>
          {% elif order.status == 'Processing' %}
            <tr>
              <th>

              {% if order.payment_status == 'Pending' %}

              {% csrf_token %}
              <a href="{% url 'payment_page' order.id %}" class="btn btn-primary">Retry Payment</a>
            {% endif %}
              </th>
              <td colspan="2">
                <a href="{% url 'create_reason' order.id %}" class="btn btn-danger">Cancel Order</a>
              </td>
            </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</div>


  <div class="card mt-4">
    <div class="card-header bg-success text-white">
      <h3 class="mb-0">Ordered Items</h3>
    </div>
    <div class="card-body">
      <table class="table table-hover ordered-items">
        <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Image</th>
            <th scope="col">Size</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for item in order.items.all %}
            <tr>
              <td>{{ item.product.name }}</td>
              <td><img src="{{ item.product.images.first.images.url }}" alt="{{ item.product.name }}" width="50" height="50"></td>
              <td>{{ item.size.measurement }}</td>
              <td>{{ item.quantity }}</td>
              <td>{{ item.total_price|floatformat:2 }}</td>
              <td>
                {% if order.status == 'Delivered' %}
                  <a href="{% url 'create_rating' product_id=item.product.id %}" class="btn btn-success">Rate Product</a>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="mt-3 invoice-download-btn">
    <a href="{% url 'generate_invoice_pdf' order.id %}" class="btn btn-primary">Download Invoice</a>
  </div>

  <div class="mt-3">
    <a href="{% url 'order_history' %}" class="btn btn-info">Order History</a>
  </div>
</div>
{% endblock %}

Jewel ecom/jewel/templates/user/order/order_successful.html
<!-- order_successful.html -->
{% extends 'user/base.html' %}

{% block content %}
    <div class="container mt-4">
        <h2 class="mb-4">Order Successful</h2>
        <p>Your order has been successfully placed. Thank you for shopping with us!</p>
        
        
<div class="mt-3">
    <a href="{% url 'home' %}" class="btn btn-primary">Continue Shopping</a>
  </div>
  
  <div class="container mt-4">
    <h2 class="mb-4">Order Details</h2>
  
    <div class="card">
      <div class="card-header bg-info text-white">
        <h3 class="mb-0">Order Information</h3>
      </div>
      <div class="card-body">
        <table class="table">
          <tbody>
            <tr>
              <th scope="row">Order ID:</th>
              <td>{{ order.id }}</td>
            </tr>
            <tr>
              <th scope="row">User:</th>
              <td>{{ order.user.username }}</td>
            </tr>
            <tr>
              <th scope="row">Address:</th>
              <td>{{ order.original_street_address }}, {{ order.original_city }}, {{ order.original_state }}, {{ order.original_postal_code }}, {{ order.original_country }}</td>
            </tr>
            <tr>
              <th scope="row">Status:</th>
              <td>{{ order.status }}</td>
            </tr>
            <tr>
              <th scope="row"> Order Value after discount:</th>
              <td>{{ order.discounted_total }}</td>
            </tr>
            {% if order.delivery_charge > 0 %}
            <tr>
                <td><strong>Delivery charge:</strong></td>
                <td>{{ order.delivery_charge }}</td>
            </tr>  {% endif %}
            {% if order.coupon_code %}
              <tr>
                <th scope="row">Coupon Applied:</th>
                <td>{{ order.coupon_code }}</td>
              </tr>
              <tr>
                <th scope="row">Discount:</th>
                <td>{{ order.coupon_discount }}</td>
              </tr>
            {% else %}
              <tr>
                <th scope="row">Coupon Applied:</th>
                <td>No Coupon Applied</td>
              </tr>
            {% endif %}
            <tr>
              <th scope="row">Payment Status:</th>
              <td>{{ order.get_payment_status_display }}</td>
            </tr>
            <tr>
              <th scope="row">Payment Method:</th>
              <td>{{ order.get_payment_method_display }}</td>
            </tr>
            {% if order.status == 'Delivered' %}
              <tr>
                <td colspan="2">
                  <a href="{% url 'return_order' order.id %}" class="btn btn-warning" onclick="return confirm('Are you sure you want to return this order?')">Return Order</a>
                </td>
              </tr>
            {% elif order.status == 'Processing' %}
              <tr>
                <td colspan="2">
                  <a href="{% url 'create_reason' order.id %}" class="btn btn-danger">Cancel Order</a>
                </td>
              </tr>
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

        <div class="card mt-4">
            <div class="card-header bg-success text-white">
                <h3 class="mb-0">Ordered Items:</h3>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Size</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{ item.product.name }}</td>
                                <td>{{ item.size.measurement }}</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.total_price|floatformat:2 }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>


        <div class="mt-4">


    <a href="{% url 'generate_invoice_pdf' order.id %}" class="btn btn-primary">Download Invoice</a>

            <a href="{% url 'order_history' %}" class="btn btn-primary">Order History</a>
        </div>
        
        <div class="mt-3">
            <a href="{% url 'home' %}" class="btn btn-primary">Continue Shopping</a>
        </div>
        
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
        
        <!-- Additional styles or summaries can be added here -->
    </div>
{% endblock %}